---
name: Test

on:
  schedule:
    - cron: '0 6 * * 5' # Every Friday at 6am UTC, to detect anton.app API changes
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: "1.4.2"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Lint
        run: bun run lint

      - name: Test
        if: >-
          github.event_name == 'workflow_dispatch' ||
          github.event_name == 'schedule' ||
          github.event.pull_request.head.repo.full_name == github.repository
        run: bun run test
        env:
          ANTON_LOGIN_CODE: ${{ secrets.ANTON_LOGIN_CODE }}
          ANTON_GROUP: Test
